### ISSUE TITLE
Issue downloading dependencies

### ISSUE THREAD

**Issue by Eqbal-Murad** [aws-samples/amazon-aiml-genai-streamlit-example#1]
environment/amazon-aiml-genai-streamlit-example (main) $ ./download-dependencies.sh 
Creating directory
Downloading dependencies
curl: (6) Could not resolve host: preview.documentation.bedrock.aws.dev
Archive:  sdk.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of sdk.zip or
        sdk.zip.zip, and cannot find sdk.zip.ZIP, period.

**Comment by alam-bilal** [comment]
For now try using this, will update url in this repo soon:
https://github.com/aws-samples/amazon-bedrock-workshop/blob/main/download-dependencies.sh
